// @ts-check

import "./types.js";

/**
 * Creates a new parser state.
 * 
 * @param {Token[]} tokens Tokens generated by lexer.
 * @param {string} source 
 * @returns {Parser}
 */
export function createParser(source, tokens) {
    return {
        source,
        tokens,
        current: 0,
        diagnostics: []
    }
}



/**
 * 
 * @param {Parser} parser Parser state. 
 * @param {number} position 
 * @returns {Token}
 */
function peekAtOffset(parser, position) {
    return parser.tokens[parser.current + position];
}

/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Token}
 */
function peek(parser) {
    return peekAtOffset(parser, 0);
}

/**
 * Checks whether the token at the given offset from the parser's current position matches any of the expected token types.
 * 
 * Positive offsets look ahead, negative offsets look behind, and `0` checks the current token.
 * 
 * This function does not consume any tokens.
 * 
 * @param {Parser} parser Parser state. 
 * @param {number} offset Offset from the current token. Can be positive, negative, or `0`.
 * @param  {...TokenType} expected Expected token types.
 * @returns {boolean} `true` if the token at the specified offset matches one of the expected types, otherwise `false`.
 */
function checkAtOffset(parser, offset, ...expected) {
    for (const type of expected) {
        if (peekAtOffset(parser, offset).type === type) {
            return true;
        }
    }

    return false;
}

/**
 * Checks whether the token at the parser's current position matches any of the expected token types.
 * 
 * This function does not consume the token.
 * 
 * @param {Parser} parser Parser state.
 * @param  {...TokenType} expected Expected types.
 * @returns {boolean} `true` if the current token matches one of the expected token types, otherwise `false`.
 */
function check(parser, ...expected) {
    return checkAtOffset(parser, 0, ...expected)
}


/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {boolean}
 */
function isAtEnd(parser) {
    return check(parser, "EndOfFile");
}



/**
 * 
 * @param {Parser} parser Parser state. 
 * @param {TokenType} [type] 
 * @param {string} [message] 
 * @returns {Token}
 */
function consume(parser, type, message) {
    if (arguments.length !== 1 && arguments.length !== 3) {
        throw new Error("consume() expects either 1 or 3 arguments.");
    }

    if (type && message) {
        if (!check(parser, type)) {
            throw message;
        }
    }

    return parser.tokens[parser.current++];
}


/**
 * 
 * @param {Parser} parser Parser state. 
 * @param  {...TokenType} expected 
 * @returns {boolean}
 */
function match(parser, ...expected) {
    for (const type of expected) {
        if (check(parser, type)) {
            consume(parser)
            return true
        }
    }

    return false
}






/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parsePrimaryExpression(parser) {
    if (match(parser, "False")) {
        return { type: "LiteralExpression", value: false };
    }
    else if (match(parser, "True")) {
        return { type: "LiteralExpression", value: true };
    }
    else if (match(parser, "Null")) {
        return { type: "LiteralExpression", value: null };
    }
    else if (check(parser, "NumericLiteral", "StringLiteral")) {
        return { type: "LiteralExpression", value: consume(parser).literal };
    }
    else if (check(parser, "Identifier")) {
        return { type: "VariableExpression", name: consume(parser) };
    }
    else if (match(parser, "LeftRoundBracket")) {
        const expression = parseExpression(parser);
        consume(parser, "RightRoundBracket", "Expect ')' after expression")
        return { type: "GroupingExpression", expression }
    }
    else if (match(parser, "LeftSquareBracket")) {
        const items = [];

        if (!match(parser, "RightSquareBracket")) {
            do {
                items.push(parseExpression(parser));
            } while (match(parser, "Comma") && !check(parser, "RightSquareBracket"));

            consume(parser, "RightSquareBracket", "Expect ']' after array literal.");
        }

        return { type: "ArrayExpression", items };
    }
    else if (check(parser, "LeftCurlyBracket")) {
        const openingCurlyBracket = consume(parser)

        const keys = [];
        const values = [];

        if (!match(parser, "RightCurlyBracket")) {
            do {
                keys.push(parseExpression(parser));

                consume(parser, "Colon", "Expect ':' between key and value in object literal.");

                values.push(parseExpression(parser));
            } while (match(parser, "Comma") && !check(parser, "RightCurlyBracket"));

            consume(parser, "RightCurlyBracket", "Expect '}' after object literal.");
        }

        return { type: "ObjectExpression", openingCurlyBracket, keys, values };
    }
    else if (match(parser, "Func")) {
        consume(parser, "LeftRoundBracket", "Expect '(' after 'func'.");

        const parameters = [];

        if (!check(parser, "RightRoundBracket")) {
            do {
                parameters.push(consume(parser, "Identifier", "Expect parameter name."));
            } while (match(parser, "Comma") && !check(parser, "RightRoundBracket"));
        }

        consume(parser, "RightRoundBracket", "Expect ')' after parameters.");

        let body;

        if (match(parser, "LeftCurlyBracket")) {
            /** @type {BlockStatement} */
            body = ({ type: "BlockStatement", statements: parseBlockBody(parser) });
        } else {
            /** @type {ReturnStatement} */
            body = ({ type: "ReturnStatement", expression: parseExpression(parser) });
        }

        return { type: "FunctionExpression", parameters, body };
    }
    else {
        throw "Expect expression."
    }
}


/**
 * 
 * @param {Parser} parser 
 * @param {Expression} object 
 * @returns {Expression}
 */
function parseIndexExpression(parser, object) {
    let index;
    let symbol;

    if (match(parser, "LeftSquareBracket")) {
        index = parseExpression(parser);
        symbol = consume(parser, "RightSquareBracket", "Expect ']' after index.");
    } else {
        symbol = consume(parser, "Dot");
        const identifier = consume(parser, "Identifier");
        /** @type {LiteralExpression} */
        index = ({ type: "LiteralExpression", value: parser.source.slice(identifier.start, identifier.end) });
    }

    return { type: "IndexExpression", object, index, symbol };
}
 
/**
 * 
 * @param {Parser} parser Parser state. 
 * @param {Expression} callee 
 * @returns {Expression}
 */
function parseCallExpression(parser, callee) {
    const arguments_ = [];

    if (!check(parser, "RightRoundBracket")) {
        do {
            arguments_.push(parseExpression(parser));
        } while (match(parser, "Comma"));
    }

    const closingRoundBracket = consume(parser, "RightRoundBracket", "Expect ')' after arguments");

    return { type: "CallExpression", callee, arguments: arguments_, closingRoundBracket };
}


/**
 * 
 * @param {Parser} parser 
 * @returns 
 */
function parsePostfixExpression(parser) {
    let expression = parsePrimaryExpression(parser);

    while (true) {
        if (match(parser, "LeftRoundBracket")) {
            expression = parseCallExpression(parser, expression);
        } else if (check(parser, "LeftSquareBracket", "Dot")) {
            expression = parseIndexExpression(parser, expression);
        } else {
            break;
        }
    }

    return expression;
}


/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parseUnaryExpression(parser) {
    if (check(parser, "ExclamationMark", "Minus")) {
        const operator = consume(parser);
        const right = parseUnaryExpression(parser);
        return { type: "UnaryExpression", right, operator };
    }

    return parsePostfixExpression(parser);
}



/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parseMultiplicationAndDivisionExpression(parser) {
    let expression = parseUnaryExpression(parser);

    while (check(parser, "Slash", "Asterisk")) {
        const operator = consume(parser)
        const right = parseUnaryExpression(parser)
        expression = { type: "BinaryExpression", left: expression, right, operator };
    }

    return expression;
}

/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parseAdditionAndSubstractionExpression(parser) {
    let expression = parseMultiplicationAndDivisionExpression(parser);

    while (check(parser, "Minus", "Plus")) {
        const operator = consume(parser)
        const right = parseMultiplicationAndDivisionExpression(parser)
        expression = { type: "BinaryExpression", left: expression, right, operator };
    }

    return expression;
}

/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parseComparisonExpression(parser) {
    let expression = parseAdditionAndSubstractionExpression(parser);

    while (check(parser, "MoreThan", "MoreThanEqual", "LessThan", "LessThanEqual")) {
        const operator = consume(parser);
        const right = parseAdditionAndSubstractionExpression(parser);

        expression = { type: "BinaryExpression", left: expression, right, operator };
    }

    return expression;
}

/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parseEqualityAndInequalityExpression(parser) {
    let expression = parseComparisonExpression(parser);

    while (check(parser, "ExclamationMarkEqual", "EqualEqual")) {
        const operator = consume(parser);
        const right = parseComparisonExpression(parser);

        expression = { type: "BinaryExpression", left: expression, right, operator };
    }

    return expression;
}


/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parseLogicalAndExpression(parser) {
    let expression = parseEqualityAndInequalityExpression(parser);

    while (check(parser, "And")) {
        const operator = consume(parser);
        const right = parseEqualityAndInequalityExpression(parser);

        expression = { type: "LogicalExpression", left: expression, right, operator };
    }

    return expression;
}


/**
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parseLogicalOrExpression(parser) {
    let expression = parseLogicalAndExpression(parser)

    while (check(parser, "Bar")) {
        const operator = consume(parser);
        const right = parseLogicalAndExpression(parser);

        expression = { type: "LogicalExpression", left: expression, right: right, operator }
    }

    return expression
}


/**
 * Parses an assignment expression.
 * 
 * ```ebnf
 * 
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parseAssignment(parser) {
    const expression = parseLogicalOrExpression(parser)

    if (check(parser, "Equal")) {
        // const equals = consume(parser); used in throw here
        const value = parseAssignment(parser);

        switch (expression.type) {
            case "VariableExpression":
                return { type: "AssignmentExpression", name: expression.name, value };
            case "IndexExpression":
                return { type: "IndexedAssignmentExpression", left: expression, value };
        }

        throw "Invalid assignment target";
    }

    return expression
}


/**
 * Parses an expression.
 * 
 * ```ebnf
 * expression = assignment
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Expression}
 */
function parseExpression(parser) {
    return parseAssignment(parser);
}


/**
 * Parses an expression statement.
 * 
 * ```ebnf
 * expression-statement = expression ";"
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement} `ExpressionStatement`
 */
function parseExpressionStatement(parser) {
    const expression = parseExpression(parser);
    consume(parser, "Semicolon", "Expect ';' after statement.");
    return { type: "ExpressionStatement", expression };
}



/**
 * Parses an if statement.
 * 
 * ```ebnf
 * if-statement = "if" "(" expression ")" statement ( "else" statement )?
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement} `IfStatement`
 */
function parseIfStatement(parser) {
    consume(parser, "LeftRoundBracket", "Expect '(' after 'if'");

    const condition = parseExpression(parser);

    consume(parser, "RightRoundBracket", "Expect ')' after if condition");

    const thenBranch = parseStatement(parser);

    let elseBranch;
    if (match(parser, "Else")) {
        elseBranch = parseStatement(parser);
    }

    return { type: "IfStatement", condition, thenBranch, elseBranch };
}


/**
 * Parses a binding. Helper function for parsing a loop statement.
 * 
 * ```ebnf
 * binding = 
 *     | Identifier
 *     | "[" Identifier ( "," Identifier )? "]"
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Binding}
 */
function parseBinding(parser) {
    let index;
    let value;

    // with i
    if (check(parser, "Identifier")) {
        value = consume(parser);
    } else {
        // with [i, value]
        consume(parser, "LeftSquareBracket", "Expect '[' after 'with'");

        index = consume(parser, "Identifier", "Expect index variable name");

        if (match(parser, "Comma")) {
            value = consume(parser, "Identifier", "Expect value variable name");
        }

        consume(parser, "RightSquareBracket", "Expect ']' after loop variables");
    }

    return { type: "Binding", index, value };
}

/**
 * Parses a loop statement.
 * 
 * ```ebnf
 * loop-statement = "loop" ( "(" expression ( "with" binding )? ")" )? statement
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement} `LoopStatement`
 */
function parseLoopStatement(parser) {
    let iterable;
    let binding;

    // loop (...)
    if (match(parser, "LeftRoundBracket")) {
        iterable = parseExpression(parser);

        if (match(parser, "With")) {
            binding = parseBinding(parser);
        }

        consume(parser, "RightRoundBracket", "Expect ')' after loop header");
    }

    const body = parseStatement(parser);

    return { type: "LoopStatement", iterable, binding, body };
}

/**
 * Parses an exit or a skip statement.
 * 
 * ```ebnf
 * exit-statement = "exit" ";"
 * skip-statement = "skip" ";"
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement} `ExitStatement` or `SkipStatement`
 */
function parseExitOrSkipStatement(parser) {
    const isExit = check(parser, "Exit");
    const keyword = consume(parser);

    consume(parser, "Semicolon", "Expect ';' after statement.");

    return { type: isExit ? "ExitStatement" : "SkipStatement", keyword };
}


/**
 * Parses a return statement.
 * 
 * ```ebnf
 *  return-statement = "return" expression? ";"
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement} `ReturnStatement`
 */
function parseReturnStatement(parser) {
    const keyword = consume(parser);

    let expression;
    if (!check(parser, "Semicolon")) {
        expression = parseExpression(parser);
    }

    consume(parser, "Semicolon", "Expect ';' after statement.")
    return { type: "ReturnStatement", keyword, expression }
}

/**
 * Parses a block body. Helper function for parsing block statement and function body.
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement[]}
 */
function parseBlockBody(parser) {
    const statements = [];

    while (!check(parser, "RightCurlyBracket") && !isAtEnd(parser)) {
        statements.push(parseDeclaration(parser));
    }

    consume(parser, "RightCurlyBracket", "Expect '}' after block");
    return statements;
}


/**
 * Parses a block statement.
 * 
 * ```ebnf
 * block-statement = "{" declarations* "}"
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement} `BlockStatement`.
 */
function parseBlockStatement(parser) {
    const statements = parseBlockBody(parser);
    return { type: "BlockStatement", statements };
}



/**
 * Parses a statement.
 * 
 * ```ebnf
 * statement = 
 *     | if-statement
 *     | loop-statement
 *     | exit-statement
 *     | skip-statement
 *     | return-statement
 *     | block-statement
 *     | expression-statement
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement}
 */
function parseStatement(parser) {
    if (match(parser, "If")) {
        return parseIfStatement(parser)
    }

    else if (match(parser, "Loop")) {
        return parseLoopStatement(parser)
    }

    else if (check(parser, "Exit", "Skip")) {
        return parseExitOrSkipStatement(parser)
    }

    else if (check(parser, "Return")) {
        return parseReturnStatement(parser)
    }

    // TODO: Maybe add lookahead for objects
    else if (match(parser, "LeftCurlyBracket")) {
        return parseBlockStatement(parser)
    }

    else {
        return parseExpressionStatement(parser);
    }
}



/**
 * Parses a variable declaration.
 * 
 * ```ebnf
 * variable-declaration = "var" Identifier ( "=" expression )? ";"
 * ```
 * 
 * @param {Parser} parser Parser state.
 * @returns {Statement} `VariableDeclaration`.
 */
function parseVariableDeclaration(parser) {
    const name = consume(parser, "Identifier", "Expected variable name.");
    let initialiser;

    if (match(parser, "Equal")) initialiser = parseExpression(parser);

    consume(parser, "Semicolon", "Expect ';' after variable declaration.");

    return { type: "VariableDeclaration", name, initialiser };
}

/**
 * Parses a constant declaration.
 * 
 * ```ebnf
 * constant-declaration = "const" Identifier "=" expression ";"
 * ```
 * 
 * @param {Parser} parser Parser state.
 * @returns {Statement} `ConstantDeclaration`.
 */
function parseConstantDeclaration(parser) {
    const name = consume(parser, "Identifier", "Expected constant name.");

    consume(parser, "Equal", "Constants must be initialised.");

    const initialiser = parseExpression(parser);

    consume(parser, "Semicolon", "Expect ';' after constant declaration.");

    return { type: "ConstantDeclaration", name, initialiser };
}


/**
 * Parses a function declaration.
 * 
 * ```ebnf
 * function-declaration = "func" Identifier "(" ( Identifier ( "," Identifier )* )? ")" block ";"
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement} `FunctionDeclaration`.
 */
function parseFunctionDeclaration(parser) {
    const name = consume(parser, "Identifier", "Expect function name.");

    consume(parser, "LeftRoundBracket", "Expect '(' after function name");

    const parameters = [];
    if (!check(parser, "RightRoundBracket")) {
        do {
            parameters.push(consume(parser, "Identifier", "Expect parameter name."));
        } while (match(parser, "Comma"));
    }

    consume(parser, "RightRoundBracket", "Expect ')' after parameters")

    consume(parser, "LeftCurlyBracket", "Expect '{' before function body.");

    const body = parseBlockBody(parser);

    return { type: "FunctionDeclaration", name, parameters, body };
}


/**
 * Parses a declaration.
 * 
 * ```ebnf
 * declaration = 
 *     | variable-declaration
 *     | constant-declaration
 *     | function-declaration
 *     | statement 
 * ```
 * 
 * @param {Parser} parser Parser state. 
 * @returns {Statement}
 */
function parseDeclaration(parser) {
    if (match(parser, "Var")) {
        return parseVariableDeclaration(parser);
    } else if (match(parser, "Const")) {
        return parseConstantDeclaration(parser);
    } else if (check(parser, "Func")) {
        return parseFunctionDeclaration(parser);
    } else {
        return parseStatement(parser);
    }
}



/**
 * Parses the tokens inside `parser` and converts it into an array of statements. 
 * 
 * ```ebnf
 * program = declaration* EndOfFile
 * ```
 * 
 * @param {Parser} parser Parser state.
 * @returns {Statement[]} Generated statements.
 */
export function parse(parser) {
    const statements = [];

    while (!isAtEnd(parser)) {
        if (!match(parser, "NewLine")) {
            statements.push(parseDeclaration(parser));
        }
    }

    return statements
}